default:
- 'watch:all'

export-all:
- clean
- export-dash
- export-sublime

export-dash:
- dash
- 'shell:reloadDash'

export-sublime:
- text-mate:sublime
- text-mate-post-export:sublime

pre-push:
- lint

lint:
- jshint
- 'jsbeautifier:lint'

watch_js:
- jsbeautifier
- lint

watch_snippets:
- export-all

fresh:
- export-all
- default
